services:
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asdf

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s



  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-cluster cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  ingestion_service:
    build:
      context: .
      dockerfile: ingestion_service/Dockerfile

    container_name: ingestion_service
    environment:
      MONGO_LOADER_URL: http://loader_service:8000/file
      IMAGE_DIRECTORY: base_images
      BOOTSTRAP_SERVERS: kafka:29092

    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  loader_service:
    build: ./loader_service
    container_name: loader_service
    environment:
      MONGO_URI: mongodb://root:asdf@mongodb:27017

    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy



volumes:
  kafka_data:
  mongodb_data:







